core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('application/', views.application, name='application'),
    path('tuitions/', views.tuitions, name='tuitions'),
    path('contact/', views.contact, name='contact'),
    path('curriculum/', views.curriculum, name='curriculum'),
    path('faq/', views.faq, name='faq'),
    path('gallery/', views.gallery, name='gallery'),
    path('history/', views.history, name='history'),
    path('leadership_team/', views.leadership_team, name='leadership_team'),
    path('teachers/', views.teachers, name='teachers'),
    path('pta_management/', views.pta_management, name='pta_management'),
    path('admission/', views.admission, name='admission'),
    path('resolutions/<slug:slug>/',
         views.resolution_detail, name='resolution'),
    path('resolutions/', views.resolutions, name='resolutions'),
    path('', views.home, name='home'),
]

euroclass/urls.py
"""euroclass URL Configuration"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('webadmin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('events/', include('events.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('favicon.ico',
         RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<slug:slug>/', views.event_detail, name='event_detail'),
    path('', views.events, name='events'),
]

news/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<slug:slug>/', views.news_detail, name='news_detail'),
    path('', views.news, name='news'),
]

core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Subject(models.Model):
    name = models.CharField(max_length=50)
    # teachers - ManyToMany
    # students - ManyToMany
    description = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Application(models.Model):
    CRECHE_ONE = 'C1'
    CRECHE_TWO = 'C2'
    CRECHE_THREE = 'C3'
    NURSERY_ONE = 'N1'
    NURSERY_TWO = 'N2'
    NURSERY_THREE = 'N3'
    PRIMARY_ONE = 'P1'
    PRIMARY_TWO = 'P2'
    PRIMARY_THREE = 'P3'
    PRIMARY_FOUR = 'P4'
    PRIMARY_FIVE = 'P5'
    PRIMARY_SIX = 'P6'
    CLASS_CHOICES = (
        (CRECHE_ONE, 'Creche One'),
        (CRECHE_TWO, 'Creche Two'),
        (CRECHE_THREE, 'Creche Three'),
        (NURSERY_ONE, 'Nursery One'),
        (NURSERY_TWO, 'Nursery Two'),
        (NURSERY_THREE, 'Nursery Three'),
        (PRIMARY_ONE, 'Primary One'),
        (PRIMARY_TWO, 'Primary Two'),
        (PRIMARY_THREE, 'Primary Three'),
        (PRIMARY_FOUR, 'Primary Four'),
        (PRIMARY_FIVE, 'Primary Five'),
        (PRIMARY_SIX, 'Primary Six'),)
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),)
    YES = 'Y'
    NO = 'N'
    YES_NO_CHOICES = (
        (YES, 'Yes'),
        (NO, 'No'),)
    full_name = models.CharField(
        max_length=100, help_text='format: Surname, Firstname Middlename')
    pupil_class = models.CharField(max_length=2, choices=CLASS_CHOICES)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    image = models.ImageField(upload_to='application')
    date_of_birth = models.DateField()
    child_id_document = models.FileField(upload_to='documents')
    father_name = models.CharField(
        max_length=100, blank=True, null=True)
    mother_name = models.CharField(
        max_length=100, blank=True, null=True)
    father_contact_number = models.CharField(
        max_length=13, blank=True, null=True)
    mother_contact_number = models.CharField(
        max_length=13, blank=True, null=True)
    father_id_document = models.FileField(
        upload_to='documents', blank=True, null=True)
    mother_id_document = models.FileField(
        upload_to='documents', blank=True, null=True)
    email = models.EmailField(blank=True)
    home_address = models.CharField(max_length=50)
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    special_assitance = models.BooleanField(
        blank=True,
        help_text='Click if the child needs any special assitance')
    areas_of_assistance = models.CharField(
        max_length=200, blank=True)

    sibling_name_1 = models.CharField(
        max_length=100, blank=True, null=True)
    dob_sibling_1 = models.DateField(blank=True, null=True)
    gender_sibling_1 = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    category_sibling_1 = models.CharField(
        max_length=50, blank=True, null=True)
    sibling_class_1 = models.CharField(
        max_length=2, choices=CLASS_CHOICES, blank=True, null=True)

    sibling_name_2 = models.CharField(
        max_length=100, blank=True, null=True)
    dob_sibling_2 = models.DateField(blank=True, null=True)
    gender_sibling_2 = models.CharField(
        max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    category_sibling_2 = models.CharField(
        max_length=50, blank=True, null=True)
    sibling_class_2 = models.CharField(
        max_length=2, choices=CLASS_CHOICES, blank=True, null=True)

    sibling_name_3 = models.CharField(
        max_length=100, blank=True, null=True)
    dob_sibling_3 = models.DateField(blank=True, null=True)
    gender_sibling_3 = models.CharField(
        max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    category_sibling_3 = models.CharField(
        max_length=50, blank=True, null=True)
    sibling_class_3 = models.CharField(
        max_length=2, choices=CLASS_CHOICES, blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name


class SchoolManagement(models.Model):
    ROLE_CHOICES = (
        ('L', 'Leadership Team'),
        ('T', 'Teachers'),
        ('A', 'Teaching Assistants'),
        ('O', 'Office Staff'),
        ('S', 'Support Staff'))
    full_name = models.CharField(max_length=100)
    role = models.CharField(max_length=1, choices=ROLE_CHOICES)
    title = models.CharField(
        max_length=25, blank=True,
        help_text='E.g: Principal, Senior Teacher')
    image = models.ImageField(upload_to='management')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'School Management'
        verbose_name = 'School Management'

    def __str__(self):
        return self.full_name


class PTAManagement(models.Model):
    full_name = models.CharField(max_length=100)
    role = models.CharField(max_length=50)
    image = models.ImageField(upload_to='management')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'PTA Management'
        verbose_name_plural = 'PTA Management'

    def __str__(self):
        return self.full_name


class PTAMeetingResolution(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=100)
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'PTA Meeting Resolution'
        verbose_name_plural = 'PTA Meeting Resolutions'

    def __str__(self):
        return self.title


class FrequentlyAskedQuestion(models.Model):
    question = models.CharField(max_length=150)
    answer = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Frequently Asked Question'
        verbose_name_plural = 'Frequently Asked Questions'

    def __str__(self):
        return self.question


class Picture(models.Model):
    caption = models.CharField(max_length=100)
    image = models.ImageField(upload_to='picture')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.caption


class Tuition(models.Model):
    NURSERY_SCHOOL = 'NS'
    PRIMARY_SCHOOL = 'PS'
    SCHOOL_TYPE_CHOICES = (
        (NURSERY_SCHOOL, 'Nursery School'),
        (PRIMARY_SCHOOL, 'Primary School'))
    tuition_info = models.CharField(
        max_length=50, help_text='3-month Terms')
    first_term_period = models.CharField(
        max_length=100, help_text='Eg. January-March')
    first_term_price = models.IntegerField()
    second_term_period = models.CharField(
        max_length=100, help_text='Eg. May-July')
    second_term_price = models.IntegerField()
    third_term_period = models.CharField(
        max_length=100, help_text='Eg. September-November')
    third_term_price = models.IntegerField()

    def __str__(self):
        return self.tuition_info

    @property
    def term_total(self):
        return self.first_term_price + self.second_term_price + self.third_term_price


class SchoolContactInfo(models.Model):
    # Add unique=True?
    short_information = models.CharField(max_length=150)
    address = models.CharField(max_length=200)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    logo = models.ImageField(upload_to='logo')
    facebook_url = models.URLField(blank=True)
    instagram_url = models.URLField(blank=True)
    twitter_url = models.URLField(blank=True)
    linkedin_url = models.URLField(blank=True)

    class Meta:
        verbose_name = 'School Contact Information'
        verbose_name_plural = 'School Contact Information'

    def __str__(self):
        return "School Contact Information"

    def save(self, *args, **kwargs):
        if not self.pk and SchoolContactInfo.objects.exists():
            raise ValidationError(
                'There can only be one SchoolContactInfo instance.')
        return super().save(*args, **kwargs)


class About(models.Model):
    welcome_note = models.TextField()
    welcome_note_image = models.ImageField(upload_to='about')
    history = RichTextUploadingField()
    history_title = models.CharField(max_length=20)
    history_image = models.ImageField(upload_to='about')
    admission_information = RichTextField()
    admission_information_image = models.ImageField(upload_to='about')

    class Meta:
        verbose_name_plural = 'About'

    def __str__(self):
        return "About School"

events/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Event(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    category = models.CharField(max_length=20)
    description = RichTextField()
    date = models.DateTimeField()
    location = models.CharField(max_length=100)
    image = models.ImageField(upload_to='events')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['date']
        get_latest_by = 'date'

    def __str__(self):
        return self.title

news/models.py
from django.db import models
from ckeditor.fields import RichTextField


# class Category(models.Model):
#     name = models.CharField(max_length=50)
#     slug = models.SlugField(max_length=50)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)

#     class Meta:
#         verbose_name_plural = 'Categories'
#         ordering = ['-created']

#     def __str__(self):
#         return self.name


class News(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150)
    image = models.ImageField(upload_to='news')
    body = RichTextField()
    # category = models.ForeignKey(Category, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'News'
        ordering = ['-created']

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from .models import Application


class ApplicationForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'form-control'}))
    dob_sibling_1 = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'form-control'}))
    dob_sibling_2 = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'form-control'}))
    dob_sibling_3 = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date', 'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'
        self.fields['full_name'].widget.attrs.update(
            {'placeholder': 'Surname, Firstname Middlename'})
        # self.fields['pupil_class'].widget.attrs.update(
        #     {'class': 'form-control'})
        # self.fields['image'].widget.attrs.update(
        #     {'class': 'form-control'})
        # self.fields['parent_name'].widget.attrs.update(
        #     {'class': 'form-control'})
        # self.fields['contact_number'].widget.attrs.update(
        #     {'class': 'form-control'})
        # self.fields['email'].widget.attrs.update(
        #     {'class': 'form-control'})
        # self.fields['home_address'].widget.attrs.update(
        #     {'class': 'form-control'})

    class Meta:
        model = Application
        exclude = ['created', 'updated']
        # fields = ['full_name', 'pupil_class', 'image',
        #           'date_of_birth', 'parent_name', 'contact_number',
        #           'email', 'home_address']


# class ContactForm(forms.ModelForm):
#     name = forms.CharField(max_length=30, required=True)
#     email = forms.EmailField(required=True)
#     phone = forms.CharField(max_length=15)
#     subject = forms.CharField(max_length=30, required=True)
#     message = forms.TextField(required=True)
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
        # for field in self.visible_fields():
        #     field.field.widget.attrs['class'] = 'form-control'

events/views.py
from django.shortcuts import render, get_object_or_404
import datetime
from .models import Event


def events(request):
    now = datetime.datetime.now()
    events = Event.objects.filter(date__gte=now)
    next_event = None
    if events.exists():
        next_event = Event.objects.filter(date__gte=now).earliest()
    return render(
        request, 'events.html',
        {'events': events, 'next_event': next_event})


def event_detail(request, slug):
    event = get_object_or_404(Event, slug=slug)
    return render(request, 'event_detail.html', {'event': event})

news/views.py
from django.shortcuts import render, get_object_or_404

from .models import News


def news(request):
    news = News.objects.all()
    return render(request, 'news.html', {'news': news})


def news_detail(request, slug):
    news = get_object_or_404(News, slug=slug)
    return render(request, 'news_detail.html', {'news': news})

templates/_alerts.html
{% if messages %}
<div class="row">
    <div class="col-12 mt-2">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>              
</div>
{% endif %}

templates/admission.html
{% extends "base.html" %}
{% block title %}Admission Information{% endblock %}

{% block content %}

<!-- Start Page Title Area -->
<div class="page-title-area bg-6">
    <div class="container">
        <div class="page-title-content">
            <h2>Admission Information</h2>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Admission Information</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Title Area -->

<!-- Start Admission Information Area -->
<section class="campus-experiences-area ptb-100">
    <div class="container">
        <div class="main-default-content">
            <p class="mb-3">{{ about.admission_information|safe }}</p>
            <a href="{% url 'application' %}" class="default-btn text-white">
                Apply for Admission
                <i class="ri-arrow-right-line"></i>
            </a>
        </div>
    </div>
</section>
<!-- End Admission Information Area -->

{% endblock %}

templates/application.html
{% extends "base.html" %}
{% block title %}Submit Application{% endblock %}

{% block content %}

<div class="page-title-area bg-27">
    <div class="container">
        <div class="page-title-content">
            <h2>Application</h2>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li class="active">Submit Application</li>
            </ul>
        </div>
    </div>
</div>

<section class="candidates-resume-area ptb-100">
    <div class="container">
        {% include '_alerts.html' %}
        {% if form.errors %}
          {% for field in form %}
          {% if field.errors %}
          <div class="alert alert-primary" role="alert">
            {{ field.label }}: {{ field.errors|striptags }}
          </div>
          {% endif %}
          {% endfor %}
          {% endif %}
        <div class="candidates-resume-content">
            <form class="resume-info" method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Pupil information</h3>
                {# form.as_p #}
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="form-group">
                            <label for="id_full_name">Name of child (required)</label>
                            {{ form.full_name }}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <div class="form-group">
                            <label for="id_gender">Gender (required)</label>
                            {{ form.gender }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <div class="form-group">
                            <label for="id_date_of_birth">Date of Birth (required)</label>
                            <div class="input-group date">
                                {{ form.date_of_birth }}
                                <span class="input-group-addon"></span>
                                <i class="bx bx-calendar"></i>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_image">Photo (required)</label>
                            {{ form.image }}
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_pupil_class">Class (required)</label>
                            {{ form.pupil_class }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_child_id_document">Pupil Document (required)</label>
                            {{ form.child_id_document }}
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="">Does the child need any special assistance, mentally or physically?</label>
                            <input type="radio" name="special_assistance" value="yes" id=""> Yes
                            <input type="radio" name="special_assistance" value="no" id=""> No
                        </div>
                    </div>
                </div>

                <h3>Parent/ Guardian's information</h3>
                <div class="row">
                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_father_name">Father's name</label>
                            {{ form.father_name }}
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_father_contact_number">Father's contact no</label>
                            {{ form.father_contact_number }}
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_father_id_document">Father's ID Document</label>
                            {{ form.father_id_document }}
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_mother_name">Mother's name</label>
                            {{ form.mother_name }}
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_mother_contact_number">Mother's contact no</label>
                            {{ form.mother_contact_number }}
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_mother_id_document">Mother's ID Document</label>
                            {{ form.mother_id_document }}
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_email">Contact E-mail</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="form-group">
                            <label for="id_home_address">Home address (required)</label>
                            {{ form.home_address }}
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2">
                        <div class="form-group">
                            <label for="id_city">City</label>
                            {{ form.city }}
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2">
                        <div class="form-group">
                            <label for="id_state">State</label>
                            {{ form.state }}
                        </div>
                    </div>
                </div>

                <h3>Details of siblings attending the school</h3>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="id_sibling_name_1">Name of sibling</label>
                            {{ form.sibling_name_1 }}
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_dob_sibling_1">Date of Birth</label>
                            <div class="input-group date">
                                {{ form.dob_sibling_1 }}
                                <span class="input-group-addon"></span>
                                <i class="bx bx-calendar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_gender_sibling_1">Gender</label>
                            {{ form.gender_sibling_1 }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_category_sibling_1">Category</label>
                            {{ form.category_sibling_1 }}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <div class="form-group">
                            <label for="id_sibling_class_1">Class</label>
                            {{ form.sibling_class_1 }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="id_sibling_name_2">Name of sibling</label>
                            {{ form.sibling_name_2 }}
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_dob_sibling_2">Date of Birth</label>
                            <div class="input-group date">
                                {{ form.dob_sibling_2 }}
                                <span class="input-group-addon"></span>
                                <i class="bx bx-calendar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_gender_sibling_2">Gender</label>
                            {{ form.gender_sibling_2 }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_category_sibling_2">Category</label>
                            {{ form.category_sibling_2 }}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <div class="form-group">
                            <label for="id_sibling_class_2">Class</label>
                            {{ form.sibling_class_2 }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>

                    <div class="col-lg-3">
                        <div class="form-group">
                            <label for="id_sibling_name_3">Name of sibling</label>
                            {{ form.sibling_name_3 }}
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_dob_sibling_3">Date of Birth</label>
                            <div class="input-group date">
                                {{ form.dob_sibling_3 }}
                                <span class="input-group-addon"></span>
                                <i class="bx bx-calendar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_gender_sibling_3">Gender</label>
                            {{ form.gender_sibling_3 }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label for="id_category_sibling_3">Category</label>
                            {{ form.category_sibling_3 }}
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <div class="form-group">
                            <label for="id_sibling_class_3">Class</label>
                            {{ form.sibling_class_3 }}
                            <i class="ri-arrow-down-s-line"></i>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <input type="submit" class="default-btn" value="Submit application">
                    </div>
                </div>

            </form>
        </div>
    </div>
</section>
<!-- End Candidates Resume Area -->

{% endblock %}

templates/history.html
{% extends "base.html" %}
{% block title %}Our School History{% endblock %}

{% block content %}
<!-- Start Page Title Area -->
<div class="page-title-area bg-6">
    <div class="container">
        <div class="page-title-content">
            <h2>Our School History</h2>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li class="active">Our School History</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Title Area -->

<!-- Start History Area -->
<section class="campus-experiences-area ptb-100">
    <div class="container">
        <div class="main-default-content">
            {{ about.history|safe }}
        </div>
    </div>
</section>
<!-- End History Area -->

{% endblock %}